---
- name: setup pre-requisites
  hosts: all
  become: yes
  become_user: root
  roles:
    - install-modules
    - configure-hosts-file

- name: install docker
  become: yes
  become_user: jayhwa_lor
  hosts: docker-nodes
  roles:
    - docker-installation

- name: initialize docker swarm
  become: yes
  become_user: jayhwa_lor
  hosts: swarm-managers
  roles:
    - docker-swarm-init

- name: add workers to the swarm
  become: yes
  become_user: jayhwa_lor
  hosts: swarm-workers
  roles:
    - docker-swarm-add-worker
