---
# - name: setup pre-requisites
#   become: yes
#   become_user: root
#   hosts: all
#   roles:
#     - create-sudo-user
#     - install-modules
#     - configure-hosts-file

# - name: setup docker user on the nodes
#   become: yes
#   become_user: docker
#   hosts: controller
#   roles:
#     - configure-admin

# - name: copy public key to nodes
#   become: yes
#   become_user: docker
#   hosts: docker-nodes
#   roles:
#     - copy-keys

# - name: install docker
#   become: yes
#   become_user: root
#   hosts: docker-nodes
#   roles:
#     - docker-installation

- name: initialize docker swarm
  become: yes
  become_user: root
  hosts: swarmmanager
  roles:
    - docker-swarm-init
  tasks:
    - debug:
        var=hostvars['swarmmanager']['worker_token']['stdout'] 


# - name: add workers to the swarm
#   become: yes
#   become_user: root
#   hosts: swarmworkers
#   roles:
#     - docker-swarm-add-worker
