---
# - name: setup pre-requisites
#   become: yes
#   become_user: root
#   hosts: all
#   roles:
#     - create-sudo-user
#     - install-modules
#     - configure-hosts-file

# - name: setup docker user on the nodes
#   become: yes
#   become_user: docker
#   hosts: admin
#   roles:
#     - configure-admin

# - name: copy public key to nodes
#   become: yes
#   become_user: docker
#   hosts: docker-nodes
#   roles:
#     - copy-keys

# - name: install docker
#   become: yes
#   become_user: root
#   hosts: docker-nodes
#   roles:
#     - docker-installation

- name: initialize docker swarm
  become: yes
  become_user: root
  hosts: swarm-manager
  roles:
    - docker-swarm-init

- name: variable troubleshooting
  hosts: docker-nodes
  tasks:
  - name:
    shell: "echo {{ hostvars['swarm-manager']['worker_token']['stdout'] }} {{ hostvars['swarm-manager']['ansible_default_ipv4']['address'] }}:2377"

- name: add workers to the swarm
  become: yes
  become_user: root
  hosts: swarm-workers
  roles:
    - docker-swarm-add-worker
