---
# - name: setup pre-requisites
#   hosts: all
#   become: yes
#   become_user: root
#   roles:
#     - create-sudo-user
#     - install-modules
#     - configure-hosts-file

- name: setup docker user on the nodes
  become: yes
  become_user: root
  hosts: controller
  roles:
    - configure-admin

- name: copy public key to nodes
  become: yes
  become_user: docker
  hosts: docker-nodes
  roles:
    - copy-keys

# - name: install docker
#   become: yes
#   become_user: root
#   hosts: docker-nodes
#   roles:
#     - docker-installation


# - name: initialize docker swarm
#   become: yes
#   become_user: root
#   hosts: swarm-managers
#   roles:
#     - docker-swarm-init


# - name: add workers to the swarm
#   become: yes
#   become_user: root
#   hosts: swarm-workers
#   roles:
#     - docker-swarm-add-worker
