---
- name: Copy Publick Key to Other Hosts
  # become: yes
  # become_user: root
  copy:
    src: /tmp/id_rsa.pub
    dest: /tmp/id_rsa.pub
    mode: 0644
- name: Append Public key in authorized_keys file
  authorized_key:
    user: docker
    state: present
    key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
