---
- name: Install Docker Dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common 
  tags: docker

- name: Get Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker packages to Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker

- name: Install Docker-CE
  apt: name="docker-ce" state=latest update_cache=yes
  tags: docker

- name: Install docker-compose from official github repo
  get_url:
    url : https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'ug+x'
