---
- name: Install Packages
  become: yes
  become_user: jayhwa_lor
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - ntp
    - python
    - tcpdump
    - wget
    - openssl
    - curl
